package builder

import "github.com/coregx/gxpdf/layout"

// PageBuilder constructs the structure of a single logical page. It provides
// three content zones — Header, Content, and Footer — each of which accepts
// a func(*Container) callback for adding elements.
//
// A page definition generated by PageBuilder may span multiple physical pages
// if the content overflows; the paginator handles the overflow automatically.
//
// PageBuilder instances are created by Builder.Page and must not be constructed
// directly.
type PageBuilder struct {
	// b is the owning Builder — used to create containers with font access.
	b *Builder
	// def accumulates the page structure.
	def pageDef
}

// Header defines the header content for this page. The header is rendered at
// the top of every physical page generated from this page definition.
//
// Example:
//
//	page.Header(func(h *builder.Container) {
//	    h.Text("ACME Corp", builder.Bold(), builder.FontSize(14))
//	})
func (p *PageBuilder) Header(fn func(*Container)) {
	c := newContainer(p.b)
	fn(c)
	p.def.header = c.elements
}

// Content defines the main body content for this page. Long content that
// exceeds the available body area is automatically split across multiple
// physical pages.
//
// Example:
//
//	page.Content(func(c *builder.Container) {
//	    c.Text("Hello World")
//	    c.Spacer(layout.Mm(5))
//	    c.Text("Second paragraph")
//	})
func (p *PageBuilder) Content(fn func(*Container)) {
	c := newContainer(p.b)
	fn(c)
	p.def.content = c.elements
}

// Footer defines the footer content for this page. The footer is rendered at
// the bottom of every physical page generated from this page definition.
//
// Example:
//
//	page.Footer(func(f *builder.Container) {
//	    f.PageNumber(
//	        layout.PageNumberPlaceholder+" / "+layout.TotalPagesPlaceholder,
//	        builder.AlignRight(), builder.FontSize(8),
//	    )
//	})
func (p *PageBuilder) Footer(fn func(*Container)) {
	c := newContainer(p.b)
	fn(c)
	p.def.footer = c.elements
}

// Size overrides the page size for this page definition. When not called,
// the document-level default from WithPageSize is used.
//
// Example:
//
//	page.Size(builder.Letter)
func (p *PageBuilder) Size(s Size) {
	ls := s.toLayout()
	p.def.size = &ls
}

// Margins overrides the page margins for this page definition. When not
// called, the document-level defaults from WithMargins are used.
//
// Example:
//
//	page.Margins(builder.Mm(25), builder.Mm(20), builder.Mm(25), builder.Mm(20))
func (p *PageBuilder) Margins(top, right, bottom, left Value) {
	m := layout.Edges{
		Top:    top.toLayout(),
		Right:  right.toLayout(),
		Bottom: bottom.toLayout(),
		Left:   left.toLayout(),
	}
	p.def.margins = &m
}
